"""notes table

Revision ID: df5b43a9380b
Revises: bca4705f798a
Create Date: 2022-04-08 17:47:25.564076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5b43a9380b'
down_revision = 'bca4705f798a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_createdAt'), 'note', ['createdAt'], unique=False)
    op.create_index(op.f('ix_note_title'), 'note', ['title'], unique=True)
    op.create_index(op.f('ix_note_updatedAt'), 'note', ['updatedAt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_updatedAt'), table_name='note')
    op.drop_index(op.f('ix_note_title'), table_name='note')
    op.drop_index(op.f('ix_note_createdAt'), table_name='note')
    op.drop_table('note')
    # ### end Alembic commands ###
